# Generated by Django 3.2.8 on 2021-11-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LungHealthDetection', '0002_alter_imageform_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageform',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
