# Generated by Django 3.2.8 on 2021-11-10 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LungHealthDetection', '0005_alter_imageform_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageform',
            name='finalusername',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AlterField(
            model_name='imageform',
            name='userid',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
